### ISSUE TITLE
Naslov v datoteki README

### ISSUE THREAD

**Issue by katjabercic** [mancazupancic/Racunalniski-praktikum#1]
V README.md datoteki v prvi vrstici piše `# racunalniski-praktikum`, moralo bi pisati `# Računalniški praktikum`. Če popravite, boste dobili točko.

Lep pozdrav,
Katja

**Comment by mancazupancic** [comment]
Pozdravljeni,
hvala za opombo, sedaj je popravljeno.

Lep pozdrav,
Manca Zupančič
